[package]
name = "flcheck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
thiserror = "1.0"
yaml-rust = "0.4.5"
